blank_issues_enabled: false
contact_links:
  - name: ğŸ“¨ ì½”ì¹­ìŠ¤í„°ë”” Data Science Projects 2024
    url: https://github.com/liebespaar93/Coaching_Study_Data_Science_Projects_2024/discussions/categories/q-a
    about: ê¶ê¸ˆí•˜ì‹  ì‚¬í•­ì„ ë¬¼ì–´ë³´ì„¸ìš”
  - name: ğŸŒ ì½”ì¹­ìŠ¤í„°ë”” Data Science Projects 2024 í”„ë¡œì íŠ¸
    url: https://github.com/users/liebespaar93/projects/6
    about: ì½”ì¹­ìŠ¤í„°ë”” í”„ë¡œì íŠ¸ ë§í¬ ì…ë‹ˆë‹¤.